// <auto-generated> from design/canvas/ds/naijakart/tokens.json (design system "Naija Kart", version 2). Do not edit: regenerate.
using UnityEngine;

namespace NaijaKart.Unity.UI
{
    /// <summary>Colour, type, spacing and motion tokens of the design system, for presenters and prefabs.</summary>
    public static class DesignTokens
    {
        /// <summary>Deepest navy. Ground behind menus and the solid base of HUD plates on Tier 1.</summary>
        public static readonly Color Plate900 = new Color(0.0275f, 0.0706f, 0.2000f, 1.000f);
        /// <summary>Surface. Cards, nav rail, sheets, menu panels.</summary>
        public static readonly Color Plate800 = new Color(0.0549f, 0.1098f, 0.2706f, 1.000f);
        /// <summary>Raised surface. Rows, tracks of bars and meters, secondary buttons.</summary>
        public static readonly Color Plate700 = new Color(0.0941f, 0.1608f, 0.3608f, 1.000f);
        /// <summary>Lines and borders. Card outlines, dividers, empty meter segments.</summary>
        public static readonly Color Plate600 = new Color(0.1647f, 0.2471f, 0.4784f, 1.000f);
        /// <summary>Frosted HUD glass over the road: position, lap, standings, speedometer, item labels, callout banners. Used with blur-glass on Tier 2 and 3 so the race stays visible through it. Text on it always takes the outline treatment.</summary>
        public static readonly Color PlateGlass = new Color(0.0392f, 0.0941f, 0.2510f, 0.380f);
        /// <summary>Glass fallback where blur is off (Tier 1, or devices without backdrop blur): more tint instead of blur, still see-through.</summary>
        public static readonly Color PlateGlassSolid = new Color(0.0275f, 0.0706f, 0.2000f, 0.620f);
        /// <summary>1px top highlight and rim on glass plates, so they read as glass against sky and road.</summary>
        public static readonly Color GlassEdge = new Color(1.0000f, 1.0000f, 1.0000f, 0.280f);
        /// <summary>Upper-half sheen on glass plates. Decoration only.</summary>
        public static readonly Color GlassSheen = new Color(1.0000f, 1.0000f, 1.0000f, 0.100f);
        /// <summary>The dark stroke and hard drop under white display text so it reads on any part of the 3D world (sky, road, billboards).</summary>
        public static readonly Color Outline = new Color(0.0157f, 0.0392f, 0.1176f, 1.000f);
        /// <summary>Primary text and icons on plate-900, plate-800, plate-700 and plate-glass (at least 12:1 on plate-700).</summary>
        public static readonly Color Ink = new Color(1.0000f, 1.0000f, 1.0000f, 1.000f);
        /// <summary>Secondary text on plate-900, plate-800 and plate-700 (at least 6.5:1).</summary>
        public static readonly Color InkMuted = new Color(0.7255f, 0.7686f, 0.8784f, 1.000f);
        /// <summary>Unavailable headings 19px or larger and empty-slot icons on plate-800. Never for text under 19px: use ink-muted there.</summary>
        public static readonly Color InkFaint = new Color(0.5059f, 0.5647f, 0.7412f, 1.000f);
        /// <summary>Primary. The one action per screen (RACE NOW, RUN AM BACK), the active nav item, and YOUR row in any standings or leaderboard.</summary>
        public static readonly Color Danfo = new Color(1.0000f, 0.7608f, 0.0549f, 1.000f);
        /// <summary>The hard bottom edge and pressed state of danfo buttons.</summary>
        public static readonly Color DanfoDeep = new Color(0.7882f, 0.5412f, 0.0000f, 1.000f);
        /// <summary>Navy text and icons on danfo (at least 11:1).</summary>
        public static readonly Color OnDanfo = new Color(0.0392f, 0.0784f, 0.2000f, 1.000f);
        /// <summary>Social: Online, Challenge, party, bail. Never a gameplay state.</summary>
        public static readonly Color Lagoon = new Color(0.0863f, 0.7804f, 0.6039f, 1.000f);
        /// <summary>Text and icons on lagoon.</summary>
        public static readonly Color OnLagoon = new Color(0.0157f, 0.1294f, 0.1020f, 1.000f);
        /// <summary>Boost: BOOST button when charged, boost callout, the boost count in the speedometer.</summary>
        public static readonly Color Boost = new Color(0.0980f, 0.8275f, 1.0000f, 1.000f);
        /// <summary>Text and icons on boost.</summary>
        public static readonly Color OnBoost = new Color(0.0118f, 0.1255f, 0.2275f, 1.000f);
        /// <summary>Rim of ItemSlot for self-boost items (Jollof Boost). Item slots only.</summary>
        public static readonly Color ItemBoost = new Color(0.2314f, 0.8902f, 0.4784f, 1.000f);
        /// <summary>Rim of ItemSlot for thrown attack items (Pure Water Attack). Item slots only.</summary>
        public static readonly Color ItemAttack = new Color(0.1843f, 0.5490f, 1.0000f, 1.000f);
        /// <summary>Rim of ItemSlot for hazards that damage others (Tire Spike). Item slots only.</summary>
        public static readonly Color ItemHazard = new Color(1.0000f, 0.2392f, 0.5451f, 1.000f);
        /// <summary>Rim of ItemSlot for traps dropped behind you (Banana Trap). Item slots only.</summary>
        public static readonly Color ItemTrap = new Color(1.0000f, 0.8157f, 0.0000f, 1.000f);
        /// <summary>Drift charge stage 1 (blue): drift ring and spark trail.</summary>
        public static readonly Color Drift1 = new Color(0.1843f, 0.5490f, 1.0000f, 1.000f);
        /// <summary>Drift charge stage 2 (orange).</summary>
        public static readonly Color Drift2 = new Color(1.0000f, 0.5412f, 0.1216f, 1.000f);
        /// <summary>Drift charge stage 3 (purple), the maximum mini-turbo.</summary>
        public static readonly Color Drift3 = new Color(0.7059f, 0.3608f, 1.0000f, 1.000f);
        /// <summary>Speedometer arc, first fifth (cyan).</summary>
        public static readonly Color Speed1 = new Color(0.0980f, 0.8275f, 1.0000f, 1.000f);
        /// <summary>Speedometer arc, second fifth (green).</summary>
        public static readonly Color Speed2 = new Color(0.2314f, 0.8902f, 0.4784f, 1.000f);
        /// <summary>Speedometer arc, middle (yellow).</summary>
        public static readonly Color Speed3 = new Color(1.0000f, 0.8157f, 0.0000f, 1.000f);
        /// <summary>Speedometer arc, fourth fifth (orange).</summary>
        public static readonly Color Speed4 = new Color(1.0000f, 0.5412f, 0.1216f, 1.000f);
        /// <summary>Speedometer arc, top speed (red).</summary>
        public static readonly Color Speed5 = new Color(1.0000f, 0.2314f, 0.3059f, 1.000f);
        /// <summary>Enforcer threat (LASTMA in Season 1), hazards aimed at you, errors.</summary>
        public static readonly Color Enforcer = new Color(1.0000f, 0.2314f, 0.3059f, 1.000f);
        /// <summary>Text and icons on enforcer fills.</summary>
        public static readonly Color OnEnforcer = new Color(0.1020f, 0.0078f, 0.0235f, 1.000f);
        /// <summary>Escaped, complete, rank up, ready. Always with a word or icon.</summary>
        public static readonly Color Success = new Color(0.2314f, 0.8902f, 0.4784f, 1.000f);
        /// <summary>Weak network, low storage, data prompts. Always with an icon.</summary>
        public static readonly Color Warning = new Color(1.0000f, 0.6235f, 0.1098f, 1.000f);
        /// <summary>Rank tier 1, JJC: badge and rank name.</summary>
        public static readonly Color RankJjc = new Color(0.6039f, 0.6392f, 0.6824f, 1.000f);
        /// <summary>Rank tier 2, Sharp Sharp.</summary>
        public static readonly Color RankSharpSharp = new Color(0.3098f, 0.7647f, 0.9686f, 1.000f);
        /// <summary>Rank tier 3, No Dull.</summary>
        public static readonly Color RankNoDull = new Color(0.2039f, 0.8196f, 0.6510f, 1.000f);
        /// <summary>Rank tier 4, Sabi.</summary>
        public static readonly Color RankSabi = new Color(0.6392f, 0.8510f, 0.3098f, 1.000f);
        /// <summary>Rank tier 5, Odogwu.</summary>
        public static readonly Color RankOdogwu = new Color(1.0000f, 0.4784f, 0.1804f, 1.000f);
        /// <summary>Rank tier 6, Chairman.</summary>
        public static readonly Color RankChairman = new Color(0.9098f, 0.7216f, 0.2902f, 1.000f);
        /// <summary>Rank tier 7, Oga Patapata. Top 100 only.</summary>
        public static readonly Color RankOgaPatapata = new Color(0.9490f, 0.3725f, 0.6588f, 1.000f);
        /// <summary>Text on any rank fill.</summary>
        public static readonly Color OnRank = new Color(0.0667f, 0.0706f, 0.0784f, 1.000f);
        /// <summary>Behind sheets over live 3D. Tier 1 uses plate-900, no blur.</summary>
        public static readonly Color Scrim = new Color(0.0157f, 0.0392f, 0.1176f, 0.720f);
        public static readonly Color Danger = Enforcer;

        public const string DisplayFontFamily = "Lilita One";
        public const string TextFontFamily = "Nunito";
        /// <summary>display-xl: Countdown, results position, rank-up reveal. Outlined white on the world.</summary>
        public static readonly TextStyle DisplayXl = new TextStyle("display", 120f, 104f, 400);
        /// <summary>display-l: Hero moments: LAST LAP, PULL OVER!, match found.</summary>
        public static readonly TextStyle DisplayL = new TextStyle("display", 72f, 68f, 400);
        /// <summary>display-m: Primary CTA label and screen titles.</summary>
        public static readonly TextStyle DisplayM = new TextStyle("display", 44f, 44f, 400);
        /// <summary>heading-l: Callout headlines, mode titles, rank names on profile.</summary>
        public static readonly TextStyle HeadingL = new TextStyle("display", 30f, 32f, 400);
        /// <summary>heading-m: Card titles, player names, callout second lines.</summary>
        public static readonly TextStyle HeadingM = new TextStyle("display", 22f, 24f, 400);
        /// <summary>heading-s: Eyebrows and small headers.</summary>
        public static readonly TextStyle HeadingS = new TextStyle("display", 17f, 20f, 400);
        /// <summary>body-l: Mode descriptions, onboarding, sheet copy.</summary>
        public static readonly TextStyle BodyL = new TextStyle("text", 17f, 24f, 700);
        /// <summary>body: Default UI text, notifications, settings.</summary>
        public static readonly TextStyle Body = new TextStyle("text", 15f, 22f, 700);
        /// <summary>body-s: Secondary lines on cards and rows.</summary>
        public static readonly TextStyle BodyS = new TextStyle("text", 13f, 18f, 700);
        /// <summary>label: Small button labels, tabs, chips. Uppercase.</summary>
        public static readonly TextStyle Label = new TextStyle("text", 14f, 16f, 900);
        /// <summary>caption: Item names under slots, chips, timestamps.</summary>
        public static readonly TextStyle Caption = new TextStyle("text", 12f, 16f, 800);
        /// <summary>num-hud: HUD position.</summary>
        public static readonly TextStyle NumHud = new TextStyle("display", 64f, 60f, 400);
        /// <summary>num-l: Speed, lap counter, chase timer.</summary>
        public static readonly TextStyle NumL = new TextStyle("display", 40f, 40f, 400);
        /// <summary>num-m: Race timer, standings positions, reward deltas.</summary>
        public static readonly TextStyle NumM = new TextStyle("display", 22f, 24f, 400);
        /// <summary>num-s: Currency chips, progress counts, stat values.</summary>
        public static readonly TextStyle NumS = new TextStyle("display", 16f, 18f, 400);

        public const float Space1 = 4f; // Icon to label, chip padding.
        public const float Space2 = 8f; // Tight stacks, standings row padding.
        public const float Space3 = 12f; // Row padding, gaps between item slots.
        public const float Space4 = 16f; // Card padding, gaps between cards.
        public const float Space5 = 24f; // Minimum safe-area inset, gaps between groups.
        public const float Space6 = 32f; // Section gaps on menus.
        public const float Space7 = 48f; // HUD clusters from the edge on tablets.
        public const float Space8 = 64f; // Hero padding around RACE NOW and results headline.
        public const float RadiusSm = 6f; // Chips, standings rows, progress bars.
        public const float RadiusMd = 12f; // Buttons, HUD plates, rank badges (small).
        public const float RadiusLg = 20f; // Cards, sheets, mode cards.
        public const float RadiusPill = 999f; // Item slots, HUD buttons, avatars, speedometer.
        public const float TouchMin = 48f; // Smallest tappable target in menus.
        public const float ButtonMd = 52f; // Secondary and danger buttons.
        public const float ButtonLg = 72f; // Primary CTA (RACE NOW, RUN AM BACK).
        public const float HudButton = 88f; // Item slots and Boost button in a race.
        public const float HudButtonDrift = 112f; // Drift button, the most-held control.
        public const float Speedometer = 176f; // Diameter of the speedometer gauge.
        public const float NavRail = 88f; // Width of the left navigation rail.
        public const float SafeInset = 24f; // Minimum inset from every edge, on top of device safe areas.
        public const float BlurGlass = 14f; // Backdrop blur behind every HUD glass plate.
        public const float BlurGlassLight = 8f; // Lighter blur for small plates (standings rows, item labels) to save GPU.
        public const float DurationFast = 0.12f; // Presses, item activation, +1, boost ignition.
        public const float DurationMedium = 0.24f; // Cards, nav changes, sheets, standings reorder.
        public const float DurationSlow = 0.6f; // Rank-up, results headline, tournament win. Never during a race.

        /// <summary>Hard-edge shadows: offset y and colour (no blur, cheap on Tier 1).</summary>
        public const string EdgeDanfo = "0 6px 0 #c98a00"; // Bottom edge of primary buttons. Collapses to 0 2px 0 on press.
        public const string EdgePlate = "0 4px 0 #040a1e"; // Bottom edge of secondary buttons, tappable cards and HUD plates.
        public const string Lift = "0 8px 24px rgba(0, 0, 0, 0.45)"; // Sheets and notification cards over 3D. Tier 2 and 3 only.

        public readonly struct TextStyle
        {
            public readonly string Family; public readonly float Size; public readonly float LineHeight; public readonly int Weight;
            public TextStyle(string family, float size, float lineHeight, int weight) { Family = family; Size = size; LineHeight = lineHeight; Weight = weight; }
        }
    }
}
