#!/usr/bin/env python3
"""Generates Assets/NaijaKart/Runtime/Unity/UI/DesignTokens.cs from design/canvas/ds/naijakart/tokens.json.

Run after editing the design tokens:  python3 -I tools/gen_design_tokens.py
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "design/canvas/ds/naijakart/tokens.json"
DST = ROOT / "Assets/NaijaKart/Runtime/Unity/UI/DesignTokens.cs"


def pascal(name):
    return "".join(p[:1].upper() + p[1:] for p in name.split("-"))


def color(value):
    v = value.strip()
    if v.startswith("#"):
        h = v[1:]
        if len(h) == 3:
            h = "".join(c * 2 for c in h)
        r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
        a = int(h[6:8], 16) / 255 if len(h) == 8 else 1.0
    else:
        m = re.match(r"rgba?\(([^)]*)\)", v)
        parts = [p.strip() for p in m.group(1).split(",")]
        r, g, b = (float(p) / 255 for p in parts[:3])
        a = float(parts[3]) if len(parts) > 3 else 1.0
    return f"new Color({r:.4f}f, {g:.4f}f, {b:.4f}f, {a:.3f}f)"


def px(value):
    v = value.strip()
    if v.endswith("ms"):
        return f"{float(v[:-2]) / 1000:g}f"
    if v.endswith("s"):
        return f"{float(v[:-1]):g}f"
    return f"{float(v.replace('px', '')):g}f"


def main():
    d = json.loads(SRC.read_text())
    out = []
    w = out.append
    w(f'// <auto-generated> from design/canvas/ds/naijakart/tokens.json (design system "{d["name"]}", version {d["version"]}). Do not edit: regenerate with python3 -I tools/gen_design_tokens.py')
    w("using UnityEngine;")
    w("")
    w("namespace NaijaKart.Unity.UI")
    w("{")
    w("    /// <summary>Colour, type, spacing and motion tokens of the design system, for presenters and prefabs.</summary>")
    w("    public static class DesignTokens")
    w("    {")
    theme = d["color"]["themes"][0]["id"]
    aliases = []
    for t in d["color"]["tokens"]:
        v = t["value"]
        if isinstance(v, str) and v.startswith("{"):
            aliases.append((pascal(t["name"]), pascal(v.strip("{}"))))
            continue
        w(f"        /// <summary>{t['usage']}</summary>")
        w(f"        public static readonly Color {pascal(t['name'])} = {color(v[theme])};")
    for name, target in aliases:
        w(f"        public static readonly Color {name} = {target};")
    w("")
    fams = d["type"]["families"]
    for key, const in (("display", "DisplayFontFamily"), ("text", "TextFontFamily")):
        first = fams[key].split(",")[0].strip().strip('"')
        w(f'        public const string {const} = "{first}";')
    for g in d["type"]["groups"]:
        for s in g["styles"]:
            w(f"        /// <summary>{s['name']}: {s['usage']}</summary>")
            w(f"        public static readonly TextStyle {pascal(s['name'])} = new TextStyle(\"{g['family']}\", {px(s['fontSize'])}, {px(s['lineHeight'])}, {s['fontWeight']});")
    w("")
    for section in ("spacing", "radius", "size", "blur", "duration"):
        for t in d[section]["tokens"]:
            w(f"        public const float {pascal(t['name'])} = {px(t['value'])}; // {t['usage']}")
    w("")
    w("        /// <summary>Hard-edge shadows: offset y and colour (no blur, cheap on Tier 1).</summary>")
    for t in d["shadow"]["tokens"]:
        w(f"        public const string {pascal(t['name'])} = \"{t['value']}\"; // {t['usage']}")
    w("")
    w("        public readonly struct TextStyle")
    w("        {")
    w("            public readonly string Family; public readonly float Size; public readonly float LineHeight; public readonly int Weight;")
    w("            public TextStyle(string family, float size, float lineHeight, int weight) { Family = family; Size = size; LineHeight = lineHeight; Weight = weight; }")
    w("        }")
    w("    }")
    w("}")
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST.relative_to(ROOT)} ({len(out)} lines)")


if __name__ == "__main__":
    sys.exit(main())
